---
title: "#30DayMapChallenge Day 18: Globe - Map Projections"
author: "Cedric Scherer"
date: "18th of October 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(maptools)
library(patchwork)
library(extrafont)

extrafont::loadfonts()

theme_set(theme_minimal())

theme_update(
  axis.ticks = element_blank(),
  axis.text = element_blank(),
  axis.title = element_blank(),
  panel.grid.major = element_blank(),
  panel.spacing = unit(0, "pt"),
  panel.background = element_rect(color = NA, 
                                  fill = "white"),
  plot.background = element_rect(color = NA, 
                                 fill = "white"),
  plot.title = element_text(family = "Merriweather Black", 
                            color = "grey25",
                            size = 24, 
                            face = "bold",
                            hjust = 0.5,
                            margin = margin(t = 48, b = 0)),
  plot.subtitle = element_text(family = "Merriweather", 
                               color = "grey25",
                               size = 18, 
                               lineheight = 1.2,
                               hjust = 0.5,
                               margin = margin(t = 0, b = 0)),
  plot.caption = element_text(family = "Merriweather", 
                              color = "grey40", 
                              size = 18, 
                              face = "bold",
                              hjust = 0.5,
                              margin = margin(t = 24, b = 18)),
  plot.margin = margin(18, 18, 18, 18)
)
```

```{r data-prep}
sf_countries <- 
  ne_countries(returnclass = "sf")

data("wrld_simpl")
sf_countries <- wrld_simpl %>% st_as_sf()
```

```{r map, fig.width = 18, fig.height = 10.9}
base_map <- 
  sf_countries %>% 
  #mutate(highlight = if_else(SOVEREIGNT %in% ))
  ggplot() +
    geom_sf(fill = "#926638",#"#f1d5b9", 
            color = "#926638", 
            size = 0.1)

## azimuthal
aeqd <-
  base_map + 
  coord_sf(crs = "+proj=aeqd +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") +
  labs(title = "\n\nAzimuthal Equidistant Projection",
       subtitle = "by Abu Rayḥan al-Biruni (c. 1000) – equidistant")

laea <-
  base_map + 
  coord_sf(crs = "+proj=laea +x_0=0 +y_0=0 +lon_0=0 +lat_0=0") +
  labs(title = "\n\nLambert Azimuthal Equal-Area Projection",
       subtitle = "by Johann Heinrich Lambert (1772) – equal-area")

## pseudocylindrical
sinus <-
  base_map + 
  coord_sf(crs = "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") +
  labs(title = "\n\nSinusoidal Projection",
       subtitle = "by unknown (c. 1600) – equal-area & equidistant")

moll <-
  base_map + 
  coord_sf(crs = "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") + 
  labs(title = "\n\nMollweide Projection",
       subtitle = "by Karl Brandan Mollweide (1805) – equal-area")

robin <-
  base_map + 
  coord_sf(crs = "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") +
  labs(title = "\n\nRobinson Projection",
       subtitle = "by Arthur H. Robinson (1963) – compromise")

## cylindrical
behr <-
  base_map + 
  coord_sf(crs = "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs") + 
  labs(title = "\n\nBehrmann Projection",
       subtitle = "by Walter Behrmann (1910) – equal-area")

merc <-
  base_map + 
  coord_sf(crs = "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") +
  labs(title = "\n\nMercator Projection",
       subtitle = "by Gerardus Mercator (1569) – conformal")

conic <-
  base_map + 
  coord_sf(crs = "+proj=vandg +lon_0=0 +x_0=0 +y_0=0 +R_A +ellps=WGS84 +datum=WGS84 +units=m +no_defs") +
  labs(title = "\n\nMercator Projection",
       subtitle = "by Gerardus Mercator (1569) – conformal")
```


```{r map, fig.width = 18, fig.height = 10.9}
## titles
title_a <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  theme(plot.title = element_text(size = 45, color = "black", family = "Open Sans ExtraBold")) +
  labs(title = '"Azimuthal"\n')
  
title_p <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  theme(plot.title = element_text(size = 45, color = "black", family = "Open Sans ExtraBold")) +
  labs(title = '"Pseudocylindrical"\n')

title_c <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  theme(plot.title = element_text(size = 45, color = "black", family = "Open Sans ExtraBold")) +
  labs(title = '"Cylindrical"\n',
       caption = "Visualization by Cédric Scherer")

aeqd + title_a + laea + sinus + title_p + moll + merc + title_c + behr + plot_layout(ncol = 3, heights = c(1, 0.66, 0.6), widths = c(1, 0, 1))

ggsave(here::here("contributions", "Day18_Globe", "Globe_Projections.pdf"), 
       width = 18, height = 23, device = cairo_pdf)
```

***

```{r session-info}
sessionInfo()
```

