---
title: "#30DayMapChallenge Day 9: Yellow - Berlin Bus by OpenStreetMaps"
author: "Cedric Scherer"
date: "7th of October 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep}
library(tidyverse)
library(sf)
library(patchwork)
library(ggtext)
library(extrafont)

extrafont::loadfonts()

theme_set(theme_void())

theme_update(
  panel.background = element_rect(fill = "black"),
  plot.background = element_rect(fill = "black"),
  plot.title = element_markdown(family = "Poppins", 
                                color = "white",
                                size = 60,
                                face = "bold",
                                hjust = 0.5,
                                margin = margin(t = 36, b = 24)),
  plot.subtitle = element_markdown(family = "Poppins", 
                                   color = "white",
                                   size = 40,
                                   face = "bold",
                                   hjust = 0.5,
                                   margin = margin(t = 18, b = 0)),
  plot.caption = element_text(family = "Poppins", 
                              color = "grey30",
                              size = 25,
                              face = "bold",
                              hjust = 0.5,
                              margin = margin(t = 6, b = 24))
)
```

```{r data-prep}
berlin_transport <- sf::read_sf(dsn = here::here("_dev", "osm_berlin_shp", "gis_osm_transport_free_1.shp"), layer = "gis_osm_transport_free_1")
berlin_districts <- sf::read_sf(dsn = here::here("_dev", "Bezirke__Berlin", "Bezirke__Berlin.shp"), layer = "Bezirke__Berlin")

berlin_transport_types <-
  berlin_transport %>% 
  mutate(type = case_when(
    str_detect(name, "^S ") & fclass %in% c("railway_station", "railway_halt") ~ "S-Bahn",
    str_detect(name, "^U ") & fclass %in% c("railway_station", "railway_halt") ~ "U-Bahn",
    fclass == "tram_stop" ~ "Tram",
    fclass == "bus_stop" ~ "Bus",
    TRUE ~ "Other"
  ))
```

```{r maps}
ubahn <-
  berlin_transport_types %>% 
  filter(type == "U-Bahn") %>% 
  group_by(name) %>% 
  slice(1) %>%  ## keep only 1 location per station
  ggplot() +
    ## dark outline map
    geom_sf(data = berlin_districts,
            color = "grey15",
            size = 9) +
    ## light thin outline map
    geom_sf(data = berlin_districts,
            color = "grey70",
            size = 1.5) +
    ## dark borders + fill
    geom_sf(data = berlin_districts,
            color = "grey20",
            fill = "#050523",
            size = 0.6) +
    ## light outline points
    geom_sf(color = "grey80",
            size = 2.3) +
    ## blue points
    geom_sf(color = "#0054b2",
            size = 1.3) +
    scale_x_continuous(limits = c(13.07, 13.78)) +
    scale_y_continuous(limits = c(52.34, 52.67)) +
    labs(x = NULL, y = NULL,
         subtitle = "<span style='color:#0054b2'>U-Bahn Stops</span>")

sbahn <-
  berlin_transport_types %>% 
  filter(type == "S-Bahn") %>%
  group_by(name) %>% 
  slice(1) %>%  ## keep only 1 location per station
  ggplot() +
    ## dark outline map
    geom_sf(data = berlin_districts,
            color = "grey15",
            size = 9) +
    ## light thin outline map
    geom_sf(data = berlin_districts,
            color = "grey70",
            size = 1.5) +
    ## dark borders + fill
    geom_sf(data = berlin_districts,
            color = "grey20",
            fill = "#081712",
            size = 0.6) +
    ## light outline points
    geom_sf(color = "grey80",
            size = 2.3) +
    ## red points
    geom_sf(color = "#038354",
            size = 1.3) +
    scale_x_continuous(limits = c(13.07, 13.78)) +
    scale_y_continuous(limits = c(52.34, 52.67)) +
    labs(x = NULL, y = NULL,
         subtitle = "<span style='color:#038354'>S-Bahn Stops</span>")

tram <-  
  berlin_transport_types %>% 
  filter(
    type == "Tram",
    st_coordinates(.)[,1] > 13.2  ## remove tram Potsdam
  ) %>%
  group_by(name) %>% 
  slice(1) %>%  ## keep only 1 location per station
  ggplot() +
    ## dark outline map
    geom_sf(data = berlin_districts,
            color = "grey15",
            size = 9) +
    ## light thin outline map
    geom_sf(data = berlin_districts,
            color = "grey70",
            size = 1.5) +
    ## dark borders + fill
    geom_sf(data = berlin_districts,
            color = "grey20",
            fill = "#190000",
            size = 0.6) +
    ## light outline points
    geom_sf(color = "grey80",
            size = 2.3) +
    ## red points
    geom_sf(color = "#ba1818",
            size = 1.3) +
    scale_x_continuous(limits = c(13.07, 13.78)) +
    scale_y_continuous(limits = c(52.34, 52.67)) +
    labs(x = NULL, y = NULL,
         subtitle = "<span style='color:#ba1818'>Tram Stops</span>")

bus <-
  berlin_transport_types %>% 
  filter(type == "Bus") %>%
  group_by(name) %>% 
  slice(1) %>%  ## keep only 1 location per station
  ggplot() +
    ## dark outline map
    geom_sf(data = berlin_districts,
            color = "grey15",
            size = 9) +
    ## light thin outline map
    geom_sf(data = berlin_districts,
            color = "grey70",
            size = 1.5) +
    ## dark borders + fill
    geom_sf(data = berlin_districts,
            color = "grey20",
            fill = "#2a2300",
            size = 0.6) +
    ## light outline points
    geom_sf(color = "grey80",
            size = 2.3) +
    ## red points
    geom_sf(color = "#e1c11e",
            size = 1.3) +
    scale_x_continuous(limits = c(13.07, 13.78)) +
    scale_y_continuous(limits = c(52.34, 52.67)) +
    labs(x = NULL, y = NULL,
         subtitle = "<span style='color:#e1c11e'>Bus Stops</span>")
```

```{r centered-title}
title <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(title = " Public Transport in Berlin",
       caption = "Visualization by Cédric Scherer  •  Data by OpenStreetMap & Geoportal Berlin")
```

```{r full-panel, fig.width = 40, fig.height = 12.5}
ubahn + sbahn + title + tram + bus + plot_layout(nrow = 1, widths = c(1, 1, 0, 1, 1))

ggsave(here::here("Day9_Yellow", "Day6to9_BlueRedGreenYellow_BerlinPublicTransport.pdf"), width = 40, height = 11.5, device = cairo_pdf)
```

***

```{r session-info}
sessionInfo()
```

