---
title: "#30DayMapChallenge Day 16: Places - Extreme Places on Earth"
author: "Cedric Scherer"
date: "16th of October 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(ggforce)
library(extrafont)

extrafont::loadfonts()

theme_set(theme_minimal())

theme_update(
  axis.ticks = element_blank(),
  axis.text = element_blank(),
  axis.title = element_blank(),
  panel.grid.major = element_blank(),
  panel.background = element_rect(color = NA, 
                                  fill = "white"),
  plot.background = element_rect(color = NA, 
                                 fill = "white"),
  plot.title = element_text(family = "Montserrat ExtraBold", 
                            color = "black",
                            size = 48, 
                            face = "bold",
                            hjust = 0.5,
                            margin = margin(t = 18, b = 0)),
  plot.subtitle = element_text(family = "Montserrat", 
                               color = "grey40",
                               size = 15, 
                               face = "plain",
                               hjust = 0.5,
                               lineheight = 1.2,
                               margin = margin(t = 6, b = 0)),
  plot.caption = element_text(family = "Montserrat", 
                              color = "grey40", 
                              size = 12, 
                              hjust = 0.5,
                              margin = margin(t = 56, b = 18)),
  legend.position = c(0.5, 0.005),
  legend.title = element_blank(),
  legend.text = element_text(family = "Montserrat", 
                             color = "black",
                             size = 15),
  legend.key.size = unit(1.3, "lines")
)
```

```{r data-prep}
sf_regions <-
  rnaturalearth::ne_download(scale = 10, 
                             category = "physical", 
                             type = "geography_regions_polys",
                             returnclass = "sf") %>% 
  st_transform(crs = "+proj=robin") %>% 
  filter(region != "Seven seas (open ocean)") %>% 
  mutate(region = factor(region, 
                         levels = c("Asia", "North America", "Africa", "Antarctica", 
                                    "Europe", "South America", "Oceania")))

sf_lakes <-
  rnaturalearth::ne_download(scale = 10, 
                             category = "physical", 
                             type = "lakes",
                             returnclass = "sf") %>% 
  st_transform(crs = "+proj=robin")

sf_ocean <-
  rnaturalearth::ne_download(scale = 10, 
                             category = "physical", 
                             type = "ocean",
                             returnclass = "sf") %>% 
  st_transform(crs = "+proj=robin")

sf_places <-
  tribble(
    ~continent,        ~category,    ~global, ~lat,         ~long,        ~place,                                  ~value,                    ~date, 
    "Europe",           "max_temp",   0,       37.983810,   23.727539,    "Athens, Greece",                        "48.0 °C (118.4 °F)",      "10 July 1977",
    "North America",    "max_temp",   1,       36.2729,     -116.5215,    "Furnace Creek, CA, USA",                "56.7 °C (134 °F)",        "10 July 1913",
    "South America",    "max_temp",   0,       -45.86413,   -67.49656,    "Rivadavia, Argentina",                  "48.9 °C (120.0 °F)",      "11 December 1905",
    #"Asia",             "max_temp",   0,       32.4225,     35.5283,      "Tirat Zvi, Israel",                     "54 °C (129 °F)",          "21 June 1942",
    "Asia",             "max_temp",   0,       31.3430,     48.7469,      "Ahvaz Airport, Iran",                   "54 °C (129 °F)",          "29 June 2017",
    "Oceania",          "max_temp",   0,       -27.5423,    135.4203,     "Oodnadatta, Australia",                 "50.7 °C (123.3 °F)",      "2 January 1960",
    "Africa",           "max_temp",   0,       33.70439,    8.96903,      "Kebili, Tunisia",                       "55 °C (131 °F)",          "7 July 1931",
    "Antarctica",       "max_temp",   0,       -63.3981,    56.9973,      "Esperanza Base",                        "17.5 °C (63.5 °F)",       "24 March 2015",
    "Europe",           "min_temp",   0,       64.2770,     57.6169,      "Ust-Shchuger, Russia",                  "−58.1 °C (−72.6 °F)",     "31 December 1978",
    "North America",    "min_temp",   0,       78.0666664,  -38.4833314,  "North Ice, Greenland",                  "−66.1 °C (−87.0 °F)",     "9 January 1954",
    "South America",    "min_temp",   0,       -45.4833,    -71.6000,     "Coyhaique Alto, Chile",                 "−37.0 °C (−34.6 °F)",     "June 2002",
    "Africa",           "min_temp",   0,       33.5333312,  -5.1166662,   "Ifrane, Morocco",                       "−23.9 °C (−11.0 °F)",     "11 February 1935",
    "Asia",             "min_temp",   0,       63.460899,   142.785812,   "Oymyakon, Russia",                      "−67.7 °C (−89.9 °F)",     "6 February 1933",
    "Oceania",          "min_temp",   0,       -36.427891,  148.333679,   "Charlotte Pass, Australia",             "−23 °C (−9 °F)",          "29 June 1994",
    "Antarctica",       "min_temp",   1,       -78.458651,  106.835726,   "Vostok Station",                        "−89.2 °C (−128.6 °F)",    "21 July 1983",
    "Europe",           "max_elev",   0,       43.355,     	42.439167,    "Mount Elbrus, Russia",                  "642 m (18,510 feet)",     NA_character_,
    "North America",    "max_elev",   0,       63.0692,	    151.007,      "Denali (Mount McKinley), AK, USA",      "6,190.5 m (20,310 feet)", NA_character_,
    "South America",    "max_elev",   0,       -32.653179,  -70.010864,   "Aconcagua, Argentina",                  "6,962 m (22,841 feet)",   NA_character_,
    "Africa",           "max_elev",   0,       -3.065653,   37.352013,    "Kilimanjaro, Tanzania",                 "5,893 m (19,334 feet)",   NA_character_,
    "Asia",             "max_elev",   1,     	 27.986065,	  86.922623,    "Mount Everest, China & Nepal",          "8,848 m (29,029 feet)",   NA_character_,
    "Oceania",          "max_elev",   0,       -4.083611,   137.184722,   "Puncak Jaya, Indonesia",                "884 m (16,024 feet)",     NA_character_,
    "Antarctica",       "max_elev",   0,       -78.5333,    -85.5833,     "Vinson Massif",                         "4,892 m (16,050 feet)",   NA_character_,
    "Europe",           "min_elev",   0,       42.966633,   47.512630,    "Caspian Sea shore, Russian Federation", "−28 m (−92 feet)",        NA_character_,
    "North America",    "min_elev",   0,       36.050229,   -116.825885,  "Badwater Basin, CA, USA",               "−85 m (−279 feet)",       NA_character_,
    "South America",    "min_elev",   0,       -49.5762,    -68.3514,     "Laguna del Carbón, Argentina",          "−105 m (−344 feet)",      NA_character_,
    "Africa",           "min_elev",   0,       11.6499974,  42.416665,    "Lake Assal, Djibouti",                  "−155 m (−509 feet)",      NA_character_,
    "Asia",             "min_elev",   1,       31.559029,   35.473190,    "Dead Sea, Israel-Jordan-Palestine",     "−424 m (−1,391 feet)",    NA_character_,
    "Oceania",          "min_elev",   0,       -28.3666652, 137.3666652,  "Lake Eyre, Australia",                  "−15 m (−49 feet)",        NA_character_,
    "Antarctica",       "min_elev",   0,       -68.5499978, 78.249999,    "Deep Lake, Vestfold Hills",             "−50 m (−164 feet)",       NA_character_,
    "Atlantic Ocean",   "depths",     0,       19.83482999, -66.75266365, "Milwaukee Deep, Puerto Rico Trench",    "8,486 m (27,841 ft)",     NA_character_,
    "Arctic Ocean",     "depths",     0,       83.0,        20.0,         "Litke Deep, Eurasian Basin",            "5,450 m (17,881 ft)",     NA_character_,
    "Indian Ocean",     "depths",     0,       -10.3166654, 109.9666628,  "Sunda Trench",                          "7,725 m (25,344 ft)",     NA_character_,
    "Mediterranen Sea", "depths",     0,       36.5666644,  21.1333328,   "Calypso Deep, Hellenic Trench",         "5,267 m (17,280 ft)",     NA_character_,
    "Pacific Ocean",    "depths",     1,       11.3166654,  142.249999,   "Challenger Deep, Mariana Trench",       "10,971 m (35,994 ft)",    NA_character_,
    "Southern Ocean",   "depths",     0,       -59.9239983, -26.1881659,  "South Sandwich Trench",                 "7,235 m (23,737 ft)",     NA_character_
  ) %>% 
  mutate(category = factor(category, 
                           levels = c("max_elev", "min_elev", "max_temp", "min_temp", "depths"),
                           labels = c("Highest elevation", "Lowest elevation", 
                                      "Highest air temperature", "Lowest air temperature", 
                                      "Greatest oceanic depths"))) %>% 
  st_as_sf(coords = c("long", "lat"), 
           crs = 4326, agr = "constant") %>% 
  st_transform(crs = "+proj=moll")

df_labels <-
  sf_places %>% 
  mutate(
    lon = st_coordinates(.)[,1],
    lat = st_coordinates(.)[,2]
  ) %>% 
  as_tibble() %>% 
  filter(global == 1) %>% 
  mutate(
    lat = case_when(
      category == "Highest air temperature" ~ lat - 500000,
      category == "Lowest air temperature" ~ lat + 500000,
      category == "Highest elevation" ~ lat - 390000,
      category == "Lowest elevation" ~ lat - 380000,
      category == "Greatest oceanic depths" ~ lat - 100000
    ),
    lon = case_when(
      category == "Highest air temperature" ~ lon - 150000,
      category == "Lowest air temperature" ~ lon + 2600000,
      category == "Highest elevation" ~ lon - 21000,
      category == "Lowest elevation" ~ lon + 5000,
      category == "Greatest oceanic depths" ~ lon - 700000
    ),
    label = glue::glue("{place}"),
    label = if_else(category == "Highest air temperature", label, str_wrap(label, 17)),
    desc = glue::glue("{category}:\n{value}")
  )
```

```{r map, fig.width = 18, fig.height = 12}
ggplot(sf_regions) + 
  ## mask some non-region and non-ocean areas
  geom_sf(data = rnaturalearth::ne_countries(returnclass = "sf") %>% 
            st_transform(crs = "+proj=moll"),
          fill = "grey76", color = NA) + 
  ## regions
  geom_sf(aes(fill = region), 
          color = NA) + 
  ## ocean
  geom_sf(data = sf_ocean, 
          color = "#d4ebf2", 
          fill = "#d4ebf2", 
          size = 0.3) +
  ## lakes
  geom_sf(data = sf_lakes, 
          fill = "#d4ebf2", 
          color = NA) + 
  ## extreme places, outer ring
  geom_sf(data = sf_places, 
          aes(color = category), 
          size = 7, 
          alpha = 0.3,
          show.legend = "point") +
  ## highlight global extremes
  geom_sf(data = sf_places %>% filter(global == 1), 
          color = "white", 
          size = 7) + 
  ## extreme places, transparent ring
  geom_sf(data = sf_places, 
          aes(color = category), 
          fill = NA, 
          size = 7, 
          shape = 21, 
          stroke = 1,
          show.legend = "point") +
  ## extreme places, inner point
  geom_sf(data = sf_places, 
          aes(color = category), 
          size = 2, 
          show.legend = "point") + 
  ## labels
  geom_mark_circle(data = df_labels,
                  aes(x = lon, y = lat, 
                      group = category, 
                      label = label,
                      description = desc), 
                  color = NA, 
                  fill = NA,
                  label.fontsize = 10, 
                  label.family = "Montserrat",
                  label.fill = "#FFFFFF66",
                  con.cap = unit(0, "mm")) +
  ## color extreme category
  scale_color_manual(values = c("#009a00", "#b76631", "#b22222", "#3a94bf", "#17008b")) +
  ## fill regions
  scale_fill_manual(values = c("grey66", "grey68", "grey70", "grey72", "grey74", "grey76", "grey78"), 
                    guide = F) +
  guides(color = guide_legend(nrow = 2,
                              label.position = "right",
                              override.aes = list(size = 5))) +
  labs(title = "Extreme Places on Earth",
       subtitle = "Extreme values of measured air temperature and elevation per continent and depth per ocean.\nGlobal extremes are higlighted in white with additional information.",
       caption = "Visualization by Cédric Scherer  •  Data by Wikipedia")

ggsave(here::here("contributions", "Day16_Places", "Places_ExtremesEarth.pdf"), 
       width = 18, height = 12.2, device = cairo_pdf)
```

***

```{r session-info}
sessionInfo()
```

