---
title: "#30DayMapChallenge - Day 10: Black & White - Popualtion of Capital Cities by UN World Urbanization Prospects"
author: "Cedric Scherer"
date: "10th of November 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r prep, message=FALSE}
## packages
library(tidyverse)
library(sf)
library(patchwork)

## ggplot theme updates
source(here::here("theme", "tidy_grey.R"))

theme_set(theme_custom(base_family = "Open Sans"))
theme_update(line = element_line(colour = "white"), 
             rect = element_rect(fill = "white", color = "white"),
             panel.border = element_rect(color = "white"))
```

```{r data}
## population of capital cities | source: https://ourworldindata.org/grapher/capital-city-population
df_capitals <- readr::read_csv(here::here("data", "capital-city-population.csv"))
## geolocation of capital cities | source: https://simplemaps.com/data/world-cities
df_cities <- readr::read_csv(here::here("data", "worldcities.csv"))
```

```{r goode-map-data}
## code for Goode homolosine projection by Claus Wilke:
## https://gist.github.com/clauswilke/783e1a8ee3233775c9c3b8bfe531e28a

## world map as sf object
sf_world <- st_as_sf(rworldmap::getMap(resolution = "low"))

## check countries with more than 1 primary capital
df_cities %>% 
  filter(capital == "primary") %>% 
  group_by(iso3) %>% 
  mutate(n = n()) %>% 
  filter(n > 1)

## Capital locations as sf object
sf_capitals <-
  df_cities %>% 
  ## clean in case there are more than 1 capital per coutnry
  mutate(
    capital = case_when(
      iso3 == "ZAF" & city != "Cape Town" ~ "not_primary",
      iso3 == "LKA" & city != "Sri Jawewardenepura Kotte" ~ "not_primary",
      iso3 == "MMR" & city != "Naypyidaw" ~ "not_primary",
      iso3 == "NLD" & city != "Amsterdam" ~ "not_primary",
      iso3 == "SWZ" & city != "Mbabane" ~ "not_primary",
      iso3 == "TZA" & city != "Dodoma" ~ "not_primary",
      iso3 == "BEN" & city != "Porto-Novo" ~ "not_primary",
      iso3 == "BOL" & city != "Sucre-Novo" ~ "not_primary",
      TRUE ~ capital
    )
  ) %>% 
  filter(capital == "primary") %>%
  dplyr::select(city, lat, lng, country, Code = iso3, population) %>% 
  st_as_sf(coords = c("lng", "lat"),
           crs = 4326) %>% 
  left_join(df_capitals) %>% 
  rename(Population = `Capital city population (UN Urbanization Prospects, 2018)`) %>% 
  filter(!is.na(Entity))

## crs for Goode projection
crs_goode <- "+proj=igh"

## projection outline in long-lat coordinates
lats <- c(
  90:-90, # right side down
  -90:0, 0:-90, # third cut bottom
  -90:0, 0:-90, # second cut bottom
  -90:0, 0:-90, # first cut bottom
  -90:90, # left side up
  90:0, 0:90, # cut top
  90 # close
)

longs <- c(
  rep(180, 181), # right side down
  rep(c(80.01, 79.99), each = 91), # third cut bottom
  rep(c(-19.99, -20.01), each = 91), # second cut bottom
  rep(c(-99.99, -100.01), each = 91), # first cut bottom
  rep(-180, 181), # left side up
  rep(c(-40.01, -39.99), each = 91), # cut top
  180 # close
)

goode_outline <- 
  list(cbind(longs, lats)) %>%
  st_polygon() %>%
  st_sfc(
    crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
  ) %>% 
  st_transform(crs = crs_goode)

## bounding box in transformed coordinates
xlim <- c(-21945470, 21963330)
ylim <- c(-9538022, 9266738)

goode_bbox <- 
  list(
    cbind(
      c(xlim[1], xlim[2], xlim[2], xlim[1], xlim[1]), 
      c(ylim[1], ylim[1], ylim[2], ylim[2], ylim[1])
    )
  ) %>%
  st_polygon() %>%
  st_sfc(crs = crs_goode)

## area outside the earth outline
goode_without <- st_difference(goode_bbox, goode_outline)
```

```{r goode-map-bw}
## map bw only
ggplot(sf_world) + 
  geom_sf(fill = "black", color = "white", size = 0.2) +
  geom_sf(data = goode_without, fill = "white", color = NA) +
  geom_sf(data = goode_outline, fill = NA, color = "black", size = 0.1) +
  geom_sf(data = sf_capitals, 
          aes(size = Population),
          shape = 21,
          color = "black", 
          fill = "white",
          stroke = 0.75,
          key_glyph = "point") +
  geom_sf(data = sf_capitals, 
          aes(size = Population),
          shape = 21, 
          color = "black", 
          fill = NA, 
          stroke = 0.75,
          key_glyph = "point") +
  scale_x_continuous(name = NULL, breaks = seq(-120, 120, by = 60)) +
  scale_y_continuous(name = NULL, breaks = seq(-60, 60, by = 30)) +
  scale_size_continuous(name = "",
                        range = c(1, 9), 
                        breaks = c(1000000, 5000000, 10000000, 30000000),
                        labels = c("1 million", "5 millions", "10 millions", "30 millions")) +
  guides(size = guide_legend(override.aes = list(color = "black", 
                                                 fill = "black", 
                                                 shape = 21))) +
  coord_sf(xlim = 0.95*xlim, 
           ylim = ylim, 
           expand = F, 
           crs = crs_goode, 
           ndiscr = 1000) +
  labs(title = "Urban Population of the World's Capital Cities",
       caption = "Visualization by Cédric Scherer  •  Data by UN World Urbanization Prospects (2018)") +
  theme(panel.background = element_rect(fill = "white", 
                                        color = "white"),
        axis.text = element_blank(),
        panel.grid.major = element_line(color = "black", 
                                        size = 0.1),
        panel.grid.minor = element_line(color = "black", 
                                        size = 0.1),
        plot.title = element_text(family = "Open Sans ExtraBold",
                                  color = "black", 
                                  size = 42, 
                                  hjust = 0.5,
                                  margin = margin(t = 12, b = 8)),
        plot.caption = element_text(color = "black", 
                                    size = 14, 
                                    face = "bold",
                                    hjust = 0.5),
        legend.position = c(0.4, 0.88), ##0.93, 0.85
        legend.key = element_rect(fill = "white", color = "white"),
        legend.text = element_text(color = "black",
                                   size = 18, 
                                   margin = margin(t = 5, b = 5)))
  
ggsave(here::here("Day10_BlackWhite", "BlackWhite_CapitalPop_bw.pdf"), 
       width = 24, height = 12, device = cairo_pdf)
```

```{r goode-map-grey}
## map with dark grey
ggplot(sf_world) + 
  geom_sf(fill = "black", color = "grey20", size = 0.2) +
  geom_sf(data = goode_without, fill = "white", color = NA) +
  geom_sf(data = goode_outline, fill = NA, color = "black", size = 0.1) +
  geom_sf(data = sf_capitals, 
          aes(size = Population),
          shape = 21,
          color = "grey40", 
          fill = "white",
          stroke = 0.25,
          key_glyph = "point") +
  geom_sf(data = sf_capitals, 
          aes(size = Population),
          shape = 21, 
          color = "grey40", 
          fill = NA, 
          stroke = 0.25,
          key_glyph = "point") +
  scale_x_continuous(name = NULL, breaks = seq(-120, 120, by = 60)) +
  scale_y_continuous(name = NULL, breaks = seq(-60, 60, by = 30)) +
  scale_size_continuous(name = "",
                        range = c(2, 20), 
                        breaks = c(1000000, 5000000, 10000000, 30000000),
                        labels = c("1 million", "5 millions", "10 millions", "30 millions")) +
  guides(size = guide_legend(override.aes = list(color = "black", 
                                                 fill = "grey60", 
                                                 shape = 21))) +
  coord_sf(xlim = 0.95*xlim, 
           ylim = ylim, 
           expand = F, 
           crs = crs_goode, 
           ndiscr = 1000) +
  labs(title = "Urban Population of the World's Capital Cities",
       caption = "Visualization by Cédric Scherer  •  Data by UN World Urbanization Prospects (2018)") +
  theme(panel.background = element_rect(fill = "grey20", 
                                        color = "white"),
        axis.text = element_blank(),
        panel.grid.major = element_line(color = "black", 
                                        size = 0.1),
        panel.grid.minor = element_line(color = "black", 
                                        size = 0.1),
        plot.title = element_text(family = "Open Sans ExtraBold",
                                  color = "black", 
                                  size = 42, 
                                  hjust = 0.5,
                                  margin = margin(t = 12, b = 8)),
        plot.caption = element_text(color = "grey60", 
                                    size = 14, 
                                    face = "bold",
                                    hjust = 0.5),
        legend.position = c(0.93, 0.93),
        legend.key = element_rect(fill = "white", color = "white"),
        legend.background = element_blank(),
        legend.text = element_text(color = "grey20",
                                   size = 18, 
                                   margin = margin(t = 14, b = 14)))
  
ggsave(here::here("Day10_BlackWhite", "BlackWhite_CapitalPop_grey.pdf"), 
       width = 24, height = 12, device = cairo_pdf)
```

***
  
```{r}
sessionInfo()
```
