---
title: "#30DayMapChallenge Day 23: Population - Changes in Population Growth by Country"
author: "Cedric Scherer"
date: "23rd of November 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(extrafont)

extrafont::loadfonts()

theme_set(theme_minimal())

theme_update(
  axis.ticks = element_blank(),
  axis.text = element_blank(),
  panel.grid.major = element_line(color = "grey88", 
                                  size = 0.5),
  panel.background = element_rect(color = NA, 
                                  fill = "grey98"),
  plot.background = element_rect(color = NA, 
                                 fill = "grey98"),
  plot.title = element_text(family = "Merriweather Sans ExtraBold", 
                            color = "black",
                            size = 42, 
                            face = "bold",
                            hjust = 0.5,
                            margin = margin(t = 24, b = 6)),
  plot.subtitle = element_text(family = "Merriweather", 
                               color = "black",
                               size = 15, 
                               face = "plain",
                               hjust = 0.5,
                               margin = margin(t = 18, b = 0)),
  plot.caption = element_text(family = "Merriweather Black", 
                              color = "grey60", 
                              size = 15, 
                              hjust = 0.5,
                              margin = margin(t = 0, b = 24)),
  legend.position = "top",
  legend.text = element_text(family = "Merriweather Sans", 
                             color = "black",
                             size = 15),
  legend.key.width = unit(7, "lines"),
  legend.key.height = unit(0.8, "lines")
)
```

```{r data-prep}
df_pop_growth <- 
  readxl::read_xls(here::here("data", "WUP2018-F08-Total_Growth_Rate.xls"), skip = 16, col_names = T) %>% 
  filter(!Index %in% c(as.character(1:14), "35", "45", "53", "59", "77", "78", "87", "88", "94", "104", "116", "135", "136", "147", "161", "178", "188", "189", "216", "225", "240", "246", "247", "250", "256", "264")) %>% 
  janitor::clean_names() %>% 
  dplyr::select(-note, -index)
  
sf_world <- st_as_sf(rworldmap::getMap(resolution = "low")) %>%
  st_transform(crs = "+proj=moll") %>% 
  dplyr::select(ISO_N3)

sf_world_pop_growth <-
  sf_world %>% 
  full_join(df_pop_growth, by = c("ISO_N3" = "country_code")) %>% 
  gather(period, change, -region_subregion_country_or_area, -ISO_N3, -geometry) %>% 
  mutate(
    period = substring(period, 2),
    period = str_replace(period, "_", "–")
  ) %>% 
  filter(ISO_N3 != -99)
```

## projection 2020-2025
```{r map-2020, fig.width = 18, fig.height = 11.9}
sf_world_pop_growth %>% 
  filter(period == "2020–2025") %>% 
  mutate(
    change = case_when(
      change < -2 ~ -2,
      change > 3 ~ 3,
      TRUE ~ change
    )
  ) %>% 
  ggplot() +
    geom_sf(data = sf_world,
            color = "grey70",
            fill = "grey80",
            lwd = 0.1) +
    geom_sf(aes(color = change, 
                fill = change), 
            lwd = 0.1,
            alpha = 0.9) +
    scale_x_continuous(breaks = seq(-180, 180, by = 30)) +
    scale_y_continuous(breaks = c(seq(-80, 80, by = 20), 85)) +
    rcartocolor::scale_color_carto_c(palette = "Fall", 
                                     na.value = "transparent", 
                                     guide = F, 
                                     direction = -1,
                                     limits = c(-2, 3)) +
    rcartocolor::scale_fill_carto_c(palette = "Fall", 
                                    na.value = "grey80",
                                    name = NULL,
                                    direction = -1,
                                    limits = c(-2, 3),
                                    breaks = -2:3,
                                    labels = c("-2%", "-1%", "±0%", "+1%", "+2%", "\u2265 +3%")) +
    guides(fill = guide_legend(title.position = "top", 
                               title.hjust = 0.5, nrow = 1,
                               label.position = "top")) +
    labs(x = NULL, y = NULL,
         title = "Changes in Population Growth 2020–2025",
         subtitle = "Average Annual Rate of Change of the Total Population by Country",
         caption = "Visualization by Cédric Scherer  •  Data by United Nations (World Urbanization Prospects 2018)")

ggsave(here::here("contributions", "Day23_Population", "Population_ChangeGlobal.pdf"),
       width = 18, height = 11.9, device = cairo_pdf)
```

## Change 1950 - 2020
```{r map-change, fig.width = 18, fig.height = 11.9}
sf_world_pop_growth %>% 
  filter(period %in% c("1950–1955", "2015–2020")) %>% 
  spread(period, change) %>% 
  mutate(
    diff = `2015–2020` - `1950–1955`,
    diff = case_when(
      diff > 3 ~ 3,
      diff < -3 ~ -3,
      TRUE ~ diff
    )
  ) %>% 
  ggplot() +
    geom_sf(data = sf_world,
            color = "grey70",
            fill = "grey80",
            lwd = 0.1) +
    geom_sf(aes(color = diff, 
                fill = diff), 
            lwd = 0.1) +
    scale_x_continuous(breaks = seq(-180, 180, by = 30)) +
    scale_y_continuous(breaks = c(seq(-80, 80, by = 20), 85)) +
    rcartocolor::scale_color_carto_c(palette = "TealRose", 
                                     na.value = "transparent", 
                                     guide = F, 
                                     direction = -1,
                                     limits = c(-2.5, 2.5)) +
    rcartocolor::scale_fill_carto_c(palette = "TealRose", 
                                    na.value = "grey80",
                                    name = NULL,
                                    direction = -1,
                                    limits = c(-3, 3),
                                    breaks = -3:3,
                                    labels = c("\u2264 -3%", "-2%", "-1%", "±0%", "+1%", "+2%", "\u2265 +3%")) +
    guides(fill = guide_legend(title.position = "top", 
                               title.hjust = 0.5, nrow = 1,
                               label.position = "top")) +
    labs(x = NULL, y = NULL,
         title = "Changes in Population Growth Rates",
         subtitle = "Differences in Average Annual Rates of Population Change (1950–1955 versus 2015–2020)",
         caption = "Visualization by Cédric Scherer  •  Data by United Nations (World Urbanization Prospects 2018)")

ggsave(here::here("contributions", "Day23_Population", "Population_ChangeGlobal_diff.pdf"),
       width = 18, height = 11.9, device = cairo_pdf)
```

## facet
```{r maps-facet, fig.width = 14.2, fig.height = 42}
sf_world_pop_growth %>% 
  mutate(
    change = case_when(
      change > 4 ~ 4,
      change < -4 ~ -4,
      TRUE ~ change
    ),
    time = as.numeric(str_sub(period, 1, 4)),
    group = (time + 10) %/% 20
  ) %>% 
  group_by(group, ISO_N3) %>% 
  summarize(
    period = min(time),
    change = mean(change, na.rm = T)
  ) %>% 
  mutate(period = glue::glue("\n{period}–{period+20}")) %>% 
  ggplot() +
    geom_sf(data = sf_world,
            color = "grey70",
            fill = "grey80",
            lwd = 0.1) +
    geom_sf(aes(color = change,
                fill = change),
            lwd = 0.1,
            alpha = 0.9) +
    scale_x_continuous(breaks = seq(-180, 180, by = 30)) +
    scale_y_continuous(breaks = c(seq(-90, 90, by = 30))) +
    rcartocolor::scale_color_carto_c(palette = "Fall", 
                                     na.value = "transparent", 
                                     guide = F, 
                                     direction = -1,
                                     limits = c(-4, 4)) +
    rcartocolor::scale_fill_carto_c(palette = "Fall", 
                                    na.value = "grey80",
                                    name = NULL,
                                    direction = -1,
                                    limits = c(-4, 4),
                                    breaks = -4:4,
                                    labels = c("\u2264 -4%", "-3%", "-2%", "-1%", "±0%", 
                                               "+1%", "+2%", "+3%", "\u2265 +4%")) +
    guides(fill = guide_legend(title.position = "top", 
                               title.hjust = 0.5, nrow = 1,
                               label.position = "top")) +
    labs(x = NULL, y = NULL,
         title = "Changes in Population Growth",
         subtitle = "Average Annual Rate of Change of the Total Population by Country",
         caption = "\nVisualization by Cédric Scherer  •  Data by United Nations (World Urbanization Prospects 2018)") + 
    facet_wrap(~ period, ncol = 1) + 
    theme(strip.text = element_text(family = "Merriweather Sans ExtraBold", 
                                    color = "grey80", 
                                    size = 30),
          panel.spacing = unit(24, "pt"),
          plot.title = element_text(size = 48),
          plot.subtitle = element_text(size = 20),
          legend.text = element_text(size = 18),
          legend.key.width = unit(6, "lines"))

ggsave(here::here("contributions", "Day23_Population", "Population_ChangeGlobal_facet.pdf"),
       width = 14.2, height = 42, device = cairo_pdf)
```

***
  
```{r session-info}
sessionInfo()
```
