---
title: "#30DayMapChallenge Day 17: Zones - Time Zones of the Earth"
author: "Cedric Scherer"
date: "17th of October 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(ggtext)
library(extrafont)

extrafont::loadfonts()

theme_set(theme_minimal())

theme_update(
  axis.ticks = element_blank(),
  axis.text = element_blank(),
  axis.title = element_blank(),
  panel.grid.major = element_blank(),
  panel.spacing = unit(0, "pt"),
  panel.background = element_rect(color = NA, 
                                  fill = "white"),
  plot.background = element_rect(color = NA, 
                                 fill = "white"),
  plot.title = element_markdown(family = "Poppins ExtraBold", 
                                color = "black",
                                size = 74, 
                                face = "bold",
                                hjust = 0.5,
                                margin = margin(t = 32, b = 0)),
  plot.caption = element_markdown(family = "Poppins", 
                                  color = "grey40", 
                                  size = 18, 
                                  face = "bold",
                                  hjust = 0.5,
                                  margin = margin(t = 0, b = 32)),
  plot.margin = margin(3, 3, 3, 3)
)
```

```{r data-prep}
data("wrld_simpl")

sf_world <- wrld_simpl %>% 
  st_as_sf()

sf_tz <-
  rnaturalearth::ne_download(scale = 10, 
                             category = "cultural", 
                             type = "time_zones",
                             returnclass = "sf") %>% 
  mutate(map_color6 = factor(map_color6))

## colors based on LaCroixColoR's "Apricot" palette
cols <- c("#D72000", "#EE6100", "#FFAD0A", "#1BB6AF", "#1C3181", "#800080")
```

```{r map, fig.width = 18, fig.height = 10.9}
ggplot(sf_tz) + 
  geom_sf(data = sf_world, 
          color = NA, 
          fill = "grey20") + 
  geom_sf(aes(color = map_color6, 
              fill = map_color6), 
          size = 0.1,
          alpha = 0.7) + 
  scale_color_manual(values = cols,
                    guide = F) +
  scale_fill_manual(values = cols,
                    guide = F) +
  labs(title = "<span style='color:#D72000'>The</span> <span style='color:#EE6100'>Time</span> <span style='color:#FFAD0A'>Zones</span> <span style='color:#1BB6AF'>of</span> <span style='color:#1C3181'>the</span> <span style='color:#800080'>World</span>",
       caption = "<span style='color:#D72000'>Visualization:</span> <span style='color:#EE6100'>Cédric</span> <span style='color:#FFAD0A'>Scherer</span>  •  <span style='color:#1BB6AF'>Data:</span> <span style='color:#1C3181'>Natural</span> <span style='color:#800080'>Earth</span>")

ggsave(here::here("contributions", "Day17_Zones", "Zones_TimezonesEarth.pdf"), 
       width = 18, height = 10.9, device = cairo_pdf)
```

```{r map-countries-only, fig.width = 18, fig.height = 10.9}
sf_ocean <-
  rnaturalearth::ne_download(scale = 10, 
                             category = "physical", 
                             type = "ocean",
                             returnclass = "sf")

ggplot(sf_tz) + 
  geom_sf(aes(color = map_color6, 
              fill = map_color6), 
          size = 0.1) + 
  geom_sf(data = sf_ocean, 
          color = "white", 
          fill = "white") + 
  geom_sf(aes(color = map_color6), 
          fill = NA,
          size = 0.3) + 
  scale_color_manual(values = cols,
                    guide = F) +
  scale_fill_manual(values = cols,
                    guide = F) +
  labs(title = "<span style='color:#D72000'>The</span> <span style='color:#EE6100'>Time</span> <span style='color:#FFAD0A'>Zones</span> <span style='color:#1BB6AF'>of</span> <span style='color:#1C3181'>the</span> <span style='color:#800080'>World</span>",
       caption = "<span style='color:#D72000'>Visualization:</span> <span style='color:#EE6100'>Cédric</span> <span style='color:#FFAD0A'>Scherer</span>  •  <span style='color:#1BB6AF'>Data:</span> <span style='color:#1C3181'>Natural</span> <span style='color:#800080'>Earth</span>")

ggsave(here::here("contributions", "Day17_Zones", "Zones_TimezonesEarth_countries.pdf"), 
       width = 18, height = 10.9, device = cairo_pdf)
```

***

```{r session-info}
sessionInfo()
```

